#
#

ifneq ($(CONFIG_LS1CV2_MACH), y)
#obj-$(CONFIG_LS1C_MACH) += ls1c300a_platform.o
#obj-$(CONFIG_LS1C_MACH) += ls1c300a_cb_v0b_platform.o
obj-$(CONFIG_LS1C_MACH) += ls1c300a_openloongson_v2.0_platform.o
else
obj-$(CONFIG_LS1CV2_MACH) += ls1c300b_platform.o
endif
