#
# Common code for all Loongson based systems
#

#obj-$(CONFIG_MACH_LOONGSON) += common/		//lxy

#
# Lemote Fuloong mini-PC (Loongson 2E-based)
#

obj-$(CONFIG_LEMOTE_FULOONG2E)  += fuloong-2e/

#
# Lemote loongson2f family machines
#

obj-$(CONFIG_LEMOTE_MACH2F)  += lemote-2f/

#obj-$(CONFIG_LS1B_MACH)  += ls1b/
obj-$(CONFIG_CPU_LS232)  += ls1x/
