obj-y	+= lme_a1.o lme_a2.o lme_a3.o lme_a4.o lme_a5.o lme_a6.o lme_a7.o lme_a8.o lme_a9.o lme_a10.o lme_a11.o lme_a12.o lme_a13.o lme_a14.o 
obj-y	+= lme_a15.o lme_a16.o lme_a17.o lme_a18.o lme_a19.o lme_a20.o lme_a21.o lme_a22.o lme_a23.o lme_a24.o lme_a25.o lme_a26.o lme_a27.o lme_a28.o 
obj-y	+= lme_a29.o lme_a30.o lme_a31.o lme_a32.o lme_a33.o 
